PRINT N'Creating Foreign Key [dbo].[FK_ORDER_CUST]...';
GO

ALTER TABLE dbo.ORDERS
    ADD CONSTRAINT FK_ORDER_CUST FOREIGN KEY (CUSTOMER_ID, CUST_REGION_CD)
    REFERENCES CUSTOMER (CUST_ID, REGION_CODE);
GO

ALTER TABLE [ORDER_DETAILS]
ADD CONSTRAINT [FK_ORDERDETAILS_ORDER] FOREIGN KEY ([ORDER_ID])
REFERENCES ORDERS ([ORDER_ID]);
GO

ALTER TABLE [dbo].[ORDER_DETAILS]
ADD CONSTRAINT [FK_ORDERDETAILS_PRODUCT] FOREIGN KEY ([PROD_ID])
REFERENCES [dbo].[PRODUCTS] ([PRODUCT_ID]);
GO

-- This PK definition will be ignored by this version of the parser
-- ALTER TABLE [dbo].[PRODUCTS] ADD CONSTRAINT [PK_PRODUCTS] PRIMARY KEY ([PRODUCT_ID]);
-- GO
